# Generated by Django 3.2.25 on 2026-05-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='برند خودرو')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='لوگو')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'برند خودرو',
                'verbose_name_plural': 'برندهای خودرو',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'دسته\u200cبندی قطعات', 'verbose_name_plural': 'دسته\u200cبندی قطعات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='دسته\u200cبندی قطعه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='لینک یوتیوب یا آپارات', null=True, verbose_name='لینک ویدیو'),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مدل')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='اسلاگ')),
                ('year_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال شروع تولید')),
                ('year_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال پایان تولید')),
                ('engine_type', models.CharField(blank=True, max_length=100, verbose_name='نوع موتور')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='products.carbrand', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'مدل خودرو',
                'verbose_name_plural': 'مدل\u200cهای خودرو',
                'ordering': ['brand__name', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_cars',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.CarModel', verbose_name='خودروهای سازگار'),
        ),
    ]
