# Generated by Django 3.2.25 on 2026-05-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20260523_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='year_end',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='year_start',
        ),
    ]
