# Generated by Django 3.2.25 on 2026-05-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20260523_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_models/'),
        ),
    ]
