# Generated by Django 3.2.25 on 2026-06-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین'),
        ),
    ]
